'use strict';
const D=window.WDAY_DATA;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const HAS_URL=!!(window.location&&window.history&&window.URLSearchParams);
const state={q:'',group:'',freq:'auto',sort:'default',metric:'',limit:80};
if(HAS_URL){const p=new window.URLSearchParams(window.location.search);for(const k of Object.keys(state))if(p.has(k))state[k]=k==='limit'?Number(p.get(k)):p.get(k);}
function sync(){if(!HAS_URL)return;const p=new window.URLSearchParams();for(const [k,v]of Object.entries(state))if(v&&v!==({freq:'auto',sort:'default',limit:80}[k]))p.set(k,v);window.history.replaceState(null,'',window.location.pathname+(p.size?'?'+p.toString():''));}
function fmt(v,m){if(v===null||v===undefined||!Number.isFinite(v))return '—';let u=m.unit||'';let n=v;let pre='',suf='';if(u==='USD'){n=v/1e6;pre='$';suf='m';}else if(u==='USD millions'){pre='$';suf='m';}else if(u==='USD billions'){pre='$';suf='bn';}else if(u==='shares'){n=v/1e6;suf='m';}else if(u==='USD/share'||u==='USD per share'){pre='$';}else if(u==='percent'||u==='%'){suf='%';}else if(u==='ratio'){suf='×';}else if(u==='basis points'){suf=' bp';}else if(u==='millions'){suf='m';}else if(u==='billions'){suf='bn';}else if(u&&u!=='count'&&u!=='employees'&&u!=='customers')suf=' '+u;return pre+n.toLocaleString('en-US',{maximumFractionDigits:Math.abs(n)<10?2:Math.abs(n)<100?1:0})+suf;}
function signed(v,suffix='%'){return v===null||v===undefined||!Number.isFinite(v)?'—':(v>0?'+':'')+v.toFixed(1)+suffix;}
function selectSeries(m,freq=state.freq){let f=freq==='auto'?m.default_frequency:freq;return (m.series[f]||[]);}
function summary(m,a){if(!a.length)return{};return a[a.length-1].growth||{};}
function growthLabel(m){return m.change_mode==='points'?' pp':'%';}
function svg(m,a,big=false){const w=big?920:160,h=big?270:52,p=big?{l:82,r:30,t:22,b:42}:{l:5,r:5,t:5,b:5};if(!a.length)return '<span class="note">No observations</span>';const vals=a.map(o=>o.value);let lo=Math.min(...vals),hi=Math.max(...vals);if(lo===hi){const d=Math.max(Math.abs(lo)*.06,1);lo-=d;hi+=d;}const first=Date.parse(a[0].date),last=Date.parse(a[a.length-1].date);const x=o=>p.l+(last===first?.5:(Date.parse(o.date)-first)/(last-first))*(w-p.l-p.r);const y=o=>h-p.b-(o.value-lo)/(hi-lo)*(h-p.t-p.b);let out=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(m.name)} history">`;if(big){for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3,yy=h-p.b-i*(h-p.t-p.b)/3;out+=`<line x1="${p.l}" x2="${w-p.r}" y1="${yy}" y2="${yy}" stroke="#dce5e9"/><text x="${p.l-10}" y="${yy+4}" text-anchor="end" fill="#6b7f8a" font-size="11">${esc(fmt(v,m))}</text>`;}out+=`<text x="${p.l}" y="${h-9}" fill="#6b7f8a" font-size="11">${esc(a[0].period)}</text><text x="${w-p.r}" y="${h-9}" text-anchor="end" fill="#6b7f8a" font-size="11">${esc(a[a.length-1].period)}</text>`;}
// Missing scheduled observations break lines. Event disclosures are unconnected dots.
const cadence=a[0]?.frequency;const gap=cadence==='quarter'?115:cadence==='annual'?400:cadence==='instant'?120:0;
if(gap&&!m.no_connect)for(let i=1;i<a.length;i++){if((Date.parse(a[i].date)-Date.parse(a[i-1].date))/86400000<=gap)out+=`<line x1="${x(a[i-1])}" y1="${y(a[i-1])}" x2="${x(a[i])}" y2="${y(a[i])}" stroke="#005f9e" stroke-width="${big?2:1.5}"/>`;}
for(const o of a)out+=`<circle cx="${x(o)}" cy="${y(o)}" r="${big?4:2.2}" fill="#005f9e"><title>${esc(o.period)} · ${esc(fmt(o.value,m))}${o.qualifier?' · '+esc(o.qualifier):''}</title></circle>`;return out+'</svg>';}
function statCell(value,label,cls=''){return `<div class="datum ${cls}"><strong>${value}</strong><small>${esc(label)}</small></div>`;}
function card(m){const a=selectSeries(m),last=a[a.length-1],g=summary(m,a),acc=g.acceleration;const color=acc>0.05?'positive':acc<-.05?'negative':'';return `<article class="metric"><div class="identity"><button class="metric-title" data-metric="${esc(m.id)}">${esc(m.name)}</button>${m.is_forecast?'<span class="pill">Target / guidance</span>':''}<div class="desc">${esc(m.description)}</div></div>${statCell(last?esc((last.qualifier?last.qualifier+' ':'')+fmt(last.value,m)):'—',last?last.period:'No matching history')}${statCell(signed(g.long_term,growthLabel(m)),g.long_term_label||'Long-term: unavailable')}${statCell(`<span class="${color}">${signed(g.yoy,growthLabel(m))}</span>`,m.change_mode==='points'?'Year-on-year change':'Latest year-on-year')}${statCell(`<span class="${color}">${signed(acc,' pp')}</span>`,m.change_mode==='points'?'Change in annual pp move':'YoY vs prior-year YoY','accel')}<button class="spark" data-metric="${esc(m.id)}" aria-label="Expand ${esc(m.name)} chart">${svg(m,a)}<small>${a.length} observations · expand ↗</small></button></article>`;}
function render(){let rows=D.metrics.filter(m=>(!state.group||m.group===state.group)&&(!state.q||(m.name+' '+m.description+' '+m.group).toLowerCase().includes(state.q.toLowerCase()))&&(state.freq==='auto'||selectSeries(m).length));if(state.sort==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort!=='default'){const k=state.sort==='growth-desc'?'yoy':'acceleration';rows.sort((a,b)=>(summary(b,selectSeries(b))[k]??-Infinity)-(summary(a,selectSeries(a))[k]??-Infinity));}let html='',group=null;for(const m of rows.slice(0,state.limit)){if(state.sort==='default'&&m.group!==group){group=m.group;html+=`<div class="grouphead"><h2>${esc(group)}</h2></div>`;}html+=card(m);}$('results').innerHTML=html||'<div class="empty">No metrics match these filters.</div>';$('more').hidden=rows.length<=state.limit;$('more').textContent=`Show more (${Math.max(0,rows.length-state.limit)} remaining)`;document.querySelectorAll('[data-metric]').forEach(b=>b.addEventListener('click',()=>openMetric(b.dataset.metric)));}
function openMetric(id){const m=D.metrics.find(m=>m.id===id);if(!m){if(HAS_URL&&D.appendix_ids?.includes(id))window.location.replace('appendix.html'+window.location.search);return;}state.metric=id;sync();$('detailGroup').textContent=m.group;$('detailTitle').textContent=m.name;let chosen=state.freq==='auto'?m.default_frequency:state.freq;if(!m.series[chosen]?.length)chosen=m.default_frequency;const a=m.series[chosen]||[],g=summary(m,a);const options=Object.keys(m.series).map(f=>`<option ${f===chosen?'selected':''} value="${esc(f)}">${esc(({quarter:'Quarterly',annual:'Annual',instant:'Point in time',ytd:'Year to date',event:'Other disclosures',ttm:'Trailing twelve months'})[f]||f)} (${m.series[f].length})</option>`).join('');let html=`<p class="detail-description">${esc(m.description)}</p><label>Period basis<select id="detailFreq">${options}</select></label><div class="metricsummary">${statCell(signed(g.long_term,growthLabel(m)),g.long_term_label||'Long-term comparison unavailable')}${statCell(signed(g.yoy,growthLabel(m)),'Latest year-on-year')}${statCell(signed(g.prior_yoy,growthLabel(m)),'Previous year-on-year')}${statCell(signed(g.acceleration,' pp'),'Acceleration / deceleration')}</div><div class="chartbox">${svg(m,a,true)}</div><p class="note">${esc(m.comparability_note||'Figures retain the reporting basis of the source. Missing observations are not estimated.')} ${m.is_forecast?'These are management expectations, not reported outcomes. Growth comparisons are suppressed.':''}</p><div class="tablewrap"><table><thead><tr><th>Period / date</th><th>Reported value</th><th>YoY / pp change</th><th>Prior YoY</th><th>Acceleration</th><th>Source / context</th></tr></thead><tbody>`;for(const o of [...a].reverse()){html+=`<tr><td>${esc(o.period)}<br><span class="note">${esc(o.date)}${o.start?' · from '+esc(o.start):''}</span></td><td class="number">${esc((o.qualifier?o.qualifier+' ':'')+fmt(o.value,m))}</td><td class="number">${signed(o.growth?.yoy,growthLabel(m))}</td><td class="number">${signed(o.growth?.prior_yoy,growthLabel(m))}</td><td class="number">${signed(o.growth?.acceleration,' pp')}</td><td><a href="${esc(o.source_url)}" target="_blank" rel="noopener">Disclosure ↗</a>${o.secondary_source_url?` · <a href="${esc(o.secondary_source_url)}" target="_blank" rel="noopener">Comparison source ↗</a>`:''}${o.source_detail?' · '+esc(o.source_detail):''}<div class="note">${esc(o.notes||'')}${o.growth?.reason?' '+esc(o.growth.reason):''}</div></td></tr>`;}html+='</tbody></table></div>';if(m.tag)html+=`<p class="note">Disclosure identifier: ${esc(m.tag)}</p>`;$('detailBody').innerHTML=html;$('detailFreq').addEventListener('change',e=>{state.freq=e.target.value;$('freq').value=state.freq;openMetric(id);render();});if(!$('detail').open)$('detail').showModal();}
function closeModal(){state.metric='';sync();$('detail').close();}
function boot(){const s=D.stats;$('summary').innerHTML=[statCell(s.metric_count,'Metric series'),statCell(s.observation_count.toLocaleString(),'Sourced observations'),statCell(s.document_count,'Source documents'),statCell('Q2 FY27','Latest reported quarter · Jul 31, 2026')].map(v=>'<div class="stat">'+v+'</div>').join('');$('coverageNotice').innerHTML=esc(D.coverage_summary)+' <a href="sources.html">Read the coverage ledger and gaps ↗</a>';for(const g of [...new Set(D.metrics.map(m=>m.group))])$('group').innerHTML+=`<option value="${esc(g)}">${esc(g)}</option>`;for(const [id,k]of [['search','q'],['group','group'],['freq','freq'],['sort','sort']]){$(id).value=state[k];$(id).addEventListener(id==='search'?'input':'change',e=>{state[k]=e.target.value;state.limit=80;sync();render();});}$('more').addEventListener('click',()=>{state.limit+=80;sync();render();});$('close').addEventListener('click',closeModal);$('detail').addEventListener('cancel',()=>{state.metric='';sync();});$('detail').addEventListener('click',e=>{if(e.target===$('detail'))closeModal();});render();if(state.metric)openMetric(state.metric);}
if(window.addEventListener)window.addEventListener('popstate',()=>{if(HAS_URL){const p=new window.URLSearchParams(window.location.search);for(const k of ['q','group','metric'])state[k]=p.get(k)||'';state.freq=p.get('freq')||'auto';state.sort=p.get('sort')||'default';state.limit=Number(p.get('limit'))||80;render();if(state.metric)openMetric(state.metric);else $('detail').close();}});
boot();
